### ISSUE TITLE
Possible issue in wire.ts for VarintBlock

### ISSUE THREAD

**Issue by potatosalad** [msolomon/argo#13]
I noticed this while reading through the code earlier today:

https://github.com/msolomon/argo/blob/4bbd1193d135960789051aa9eb1bb031b44ae387/argo-js/src/wire.ts#L57-L64

Should line 57 actually read?

```typescript
  const VarintBlock = block(Wire.VARINT, 'Int', deduplicateByDefault(Wire.VARINT))
```

I think currently this would just throw at encoding or decoding time:

https://github.com/msolomon/argo/blob/4bbd1193d135960789051aa9eb1bb031b44ae387/argo-js/src/encoder.ts#L102-L104

**Comment by msolomon** [comment]
Yep, that's a bug! Will fix.
