### ISSUE TITLE
Fragment scalar merge issue

### ISSUE THREAD

**Issue by jbourassa** [msolomon/argo#14]
The reference implementation errors when merging scalars in fragments. For example, this query on the StarWars schema fails:

```graphql
query {
  hero {
    ... on Droid { name }
    ... on Human { name }
  }
}
```

The error is from:
https://github.com/msolomon/argo/blob/d1d0d53023d3f1170b1173bc6c2266243398df1c/argo-js/src/typer.ts#L287

See https://github.com/msolomon/argo/compare/main...jbourassa:argo:scalar-merge for a failing test and a potential fix.

----

The Ruby implementation had the same bug, which is based more on the spec than the reference implementation. Would we consider updating the spec to consider this case?

**Comment by msolomon** [comment]
Thanks for reporting and fixing! I stole your test and implemented it slightly differently and clarified the spec in #17 , let me know if you notice anything amiss there.

**Comment by jbourassa** [comment]
> let me know if you notice anything amiss there.

The addition to the spec is great, and the fix is quite close to the Ruby implementation 😄.


Thank you Mike!
